function(umi_platform_apply_warnings target)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4)
        if(UMICOM_PLATFORM_WARNINGS_AS_ERRORS)
            target_compile_options(${target} PRIVATE /WX)
        endif()
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
        if(UMICOM_PLATFORM_WARNINGS_AS_ERRORS)
            target_compile_options(${target} PRIVATE -Werror)
        endif()
    endif()
endfunction()
